name: Daily Run

on:
  schedule:
    # # At 18:50 UTC on everyday (12.20 mid night in Sri Lanka)
    - cron: "50 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7         
          
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Generate Course data"
        run: |
          cd ./python_scripts/
          python3 generate_course_pages.py
          cd ../

      - name: "Create and update the semester pages"
        run: |
          cd ./python_scripts/
          python3 generate_semester_pages.py
          cd ../

      - name: "Create and update the course pages"
        run: |
          cd ./python_scripts/
          python3 generate_course_pages.py
          cd ../

      - name: "Unit test for API validity"
        run: |
          cd ./python_scripts/unitTests
          python3 test_api.py
          cd ../

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Repo was updated by GitHub Actions" || echo "No changes to commit on the repo"
          git push